### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount" : 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount" : 100
}


### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "88753da87aaf4961915eedd63afd8f29",
  "accountNumber": "1000000002",
  "amount" : 100
}

### query transaction
GET http://localhost:8080/transaction/1d09f2cd14ac48a4a549a1fad07219db